# Grok palette rendered by Omarchy from the active theme (omarchy-theme-set-templates).
# grok-omarchy overlays these colors on Grok Night or Grok Day, chosen by `base`.
# Fenced-code syntax highlighting keeps Grok's baked night/day tmTheme.

base = "{{ theme_type }}"

[colors]
bg_base = "{{ background }}"
bg_light = "{{ lighter_background }}"
bg_dark = "{{ dark_background }}"
bg_highlight = "{{ lighter_background }}"
bg_hover = "{{ selection_background }}"
bg_terminal = "{{ darker_background }}"
bg_visual = "{{ selection_background }}"
accent_user = "{{ accent }}"
accent_assistant = "{{ magenta }}"
accent_thinking = "{{ muted }}"
accent_tool = "{{ dark_foreground }}"
accent_system = "{{ blue }}"
accent_error = "{{ red }}"
accent_success = "{{ green }}"
accent_running = "{{ magenta }}"
accent_skill = "{{ cyan }}"
accent_plan = "{{ yellow }}"
accent_verify = "{{ magenta }}"
accent_remember = "{{ green }}"
accent_model = "{{ bright_cyan }}"
text_primary = "{{ bright_foreground }}"
text_secondary = "{{ foreground }}"
gray_dim = "{{ muted }}"
gray = "{{ dark_foreground }}"
gray_bright = "{{ light_foreground }}"
command = "{{ yellow }}"
path = "{{ orange }}"
running = "{{ cyan }}"
warning = "{{ yellow }}"
fuzzy_accent = "{{ accent }}"
selection_border = "{{ accent }}"
hover_border = "{{ muted }}"
prompt_border = "{{ muted }}"
prompt_border_active = "{{ accent }}"
scrollbar_bg = "{{ dark_background }}"
scrollbar_fg = "{{ muted }}"
diff_delete_bg = "{{ mix background red 15% }}"
diff_delete_fg = "{{ red }}"
diff_insert_bg = "{{ mix background green 15% }}"
diff_insert_fg = "{{ green }}"
diff_equal_fg = "{{ muted }}"
diff_gutter_fg = "{{ muted }}"
paste_bg = "{{ dark_background }}"
paste_fg = "{{ foreground }}"
paste_dim = "{{ muted }}"
md_heading_h1 = "{{ bright_cyan }}"
md_heading_h2 = "{{ blue }}"
md_heading_h3 = "{{ orange }}"
md_heading_h4 = "{{ red }}"
md_heading_h5 = "{{ green }}"
md_heading_h6 = "{{ magenta }}"
md_code = "{{ bright_cyan }}"
md_task_checked = "{{ green }}"
md_task_unchecked = "{{ blue }}"
md_muted = "{{ muted }}"
md_code_bg = "{{ lighter_background }}"
md_text = "{{ bright_foreground }}"
link_fg = "{{ accent }}"
